/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersList.java
 *
 * Created on May 5, 2010, 12:53:38 PM
 */
package comapp;

import communicator.DB.DBModel;
import communicator.DB.User;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author flyhigh
 */
public class UsersList extends javax.swing.JInternalFrame {

    /** Creates new form UsersList */
    DefaultTableModel dtm;

    public UsersList() {
        createModel();
        initComponents();
        jTable1.setModel(dtm);

    }

    void createModel() {
        String[] columns = {"Employee Id",
            "Name",
            "Phone",
            "IP"
        };
        System.out.print("inside constrctr");
        ArrayList al = new DBModel().getAllUsers();
        Iterator i = al.iterator();
        int count = 0;
        System.out.print("Counting");
        while (i.hasNext()) {
            count++;
            i.next();
        }
        i = al.iterator();
        String[][] s = new String[count][4];
        int ii = 0;
        System.out.print("populate");
        while (i.hasNext()) {
            User u = (User) i.next();
            s[ii][0] = u.getEmpId();
            s[ii][1] = u.getUsername();
            s[ii][2] = u.getPhone();
            s[ii][3] = u.getIp();
            ii++;
        }
        dtm = new DefaultTableModel(s, columns);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setName("Form"); // NOI18N
        setRequestFocusEnabled(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(dtm);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 127) {
            //jTable1.getColumn(iconable).
            //System.out.println(jTable1.getRowSorter().getModel().getValueAt(jTable1.getSelectedRow(), 0));
            if (JOptionPane.showConfirmDialog(this, "You are about to delete the employee pernamently","Attention",JOptionPane.OK_CANCEL_OPTION) == 0) {
                System.out.println(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
                new DBModel().deleteUser((String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
                createModel();
                jTable1.setModel(dtm);
            }

        }
    }//GEN-LAST:event_jTable1KeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
